[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared", version = "0.1.0" }
tonic = { workspace = true, default-features = false, features = ["channel"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
